### ISSUE TITLE
keyboard and hover select operate independently

### ISSUE THREAD

**Issue by KyleAMathews** [davidtheclark/react-aria-menubutton#18]
You can select a menu item by pressing the down arrow while at the same time select another item with your mouse.

**Comment by davidtheclark** [comment]
The down arrow shouldn't actually *select* anything: it just moves the focus from one item to another.

Do you mean that you can *focus* on one element and *hover* on another at the same time? Because if so, I'm not sure that's a bug. That seems pretty normal to me. Can you explain more about why this is a problem?

**Comment by KyleAMathews** [comment]
Hmm... ok I might of misspoke. Looking around at some other menus out there that seems the normal pattern. In the past, when I've implemented something like this, I've made sure that only the mouse or keyboard was controlling focus at any one time.

**Comment by bobthecow** [comment]
I'm with @KyleAMathews :)

I'd at least like the option of changing focus via mouse hover. Basically exactly what OS X native menus do. If I implemented that, would you accept a pull request?

**Comment by davidtheclark** [comment]
@bobthecow Sure. I think it should be triggered by an option, though.

**Comment by dkniffin** [comment]
@bobthecow Did you ever end up making a PR for this? I have a user requesting this feature on my app right now.
