### ISSUE TITLE
disabled menus

### ISSUE THREAD

**Issue by AsaAyers** [davidtheclark/react-aria-menubutton#31]
I don't see any options to have a menu disabled. Is it just not supported?

My use case is that I have one menu (section) that depends on the value of another (term). This is a screenshot of some Backbone code that I'm converting to React and would like to use `react-aria-menubutton`.

![selection_121](https://cloud.githubusercontent.com/assets/324999/10792739/6152c504-7d64-11e5-97f3-b250aef0f93b.png)

**Comment by davidtheclark** [comment]
You are right. Thanks!

The content of the Button would still be in your hands, so styling it to *look* disabled would be up to you.

So we'd just have to change some attributes ... Do you think I'm right that this is all we'd need to change:

- Add `aria-disabled=true` attribute to the disabled Button element.
- Give the disabled Button element a `tabIndex` of `-1` instead of `0`, so that it's not in the tab order.

Anything else?

**Comment by AsaAyers** [comment]
The click handler also needs to be blocked. I don't think a negative tab in
index does that.

**Comment by davidtheclark** [comment]
Good point. And the enter/space keys that would do the same thing as click.

**Comment by AsaAyers** [comment]
I'm temporarily stuck back on 0.8, but hoping this can get fixed for when I do upgrade.

In 0.8 it has a Manager that holds the state. I think `toggleState()` (or whatever the current equivalent) needs to just not open when it's disabled.

**Comment by davidtheclark** [comment]
I will try to find some time this weekend to add this feature.

**Comment by AsaAyers** [comment]
Thanks :)

**Comment by davidtheclark** [comment]
Released in 3.1.0
