### ISSUE TITLE
Control menu position

### ISSUE THREAD

**Issue by HriBB** [davidtheclark/react-aria-menubutton#32]
Hello. Nice component ;) Simple and extensible, just the way I like it :)

I have a use case I can't figure out. I have a breadcrumb component where the last item is always menubutton. On large screens everything is ok, but on smaller devices, it can of course happen that button is rendered very close to the right edge, and when you click on it, menu is positioned partially outside of the viewport.

How can we "fix" the position of the menu so that it always fits inside viewport?

**Comment by davidtheclark** [comment]
This is just a matter of your own CSS, so I'm going to close this one. But I can try to help you figure it out.

If you have your menu absolutely positioned beneath your button, have you tried `right: 0;` instead of `left: 0`? That's what I do in my own menus.

**Comment by davidtheclark** [comment]
That should work if you know that your menu should open so that it sticks out to the left instead of sticking out to the right. If, however, you want to dynamically determine which way the menu should open based on its position and width when it opens — that's going to require a bunch of other calculations and much more complication.
