### ISSUE TITLE
open/close Menu using onMouseEnter on Button and onMouseLeave on Wrapper

### ISSUE THREAD

**Issue by davedc** [davidtheclark/react-aria-menubutton#40]
Hi @davidtheclark,

Is there a way to do this currently?

Thanks for the great component!

**Comment by davidtheclark** [comment]
Thanks! I think it's a good request. 

One way to go about this would be to expose methods for programmatically opening and closing the menu. (This is probably a good idea regardless.)

Another way would be to expose `openOnHover` and `openOnFocus` props.

I'll think about it sometime soonish. And if you feel like putting together an idea, PRs welcome.

**Comment by davedc** [comment]
Thanks Dave!

**Comment by davidtheclark** [comment]
I am going to push a release soon with `openMenu()` and `closeMenu()` functions. But I am also open to a PR adding the hover/focus functionality you ask for.

**Comment by souporserious** [comment]
Do you need help with this? I think the `openMenu` and `closeMenu` methods are great since it allows for outside control as well as the hover functionality. I can put together another PR for this if you haven't and would like me to @davidtheclark. I have a react select menu that [does this right now](https://github.com/souporserious/selectly/blob/master/src/Select.jsx#L75-L77) but want to swap out the open/close functionality with this lib. Maybe even just one method like `setMenuOpen` which accepts true or false could work.

**Comment by davidtheclark** [comment]
`openMenu` and `closeMenu` are now part of the API, so closing.

**Comment by oyeanuj** [comment]
@davedc @souporserious How did you end up making it open/close on hover?

@davidtheclark  When I try doing the setup the title described, it opens fine on hover but as soon as the mouse goes from the button to the menu, it closes - am I missing something basic in the setup?
