### ISSUE TITLE
Is it possible to change down/up keys to left/right?

### ISSUE THREAD

**Issue by diegohaz** [davidtheclark/react-aria-menubutton#44]
I'm making a horizontal menu

**Comment by davidtheclark** [comment]
Not currently, but should be pretty easy to add a prop for it since this uses `focus-group` (https://github.com/davidtheclark/react-aria-menubutton/blob/master/lib/createManager.js#L5) which has the option to changes forward and back arrows: https://github.com/davidtheclark/focus-group#options. PR welcome!

**Comment by diegohaz** [comment]
I'll see this today. :)
I think the better option would be to pass all props to focusGroup. It will solve some future needs.

**Comment by jamsea** [comment]
@diegohaz Did you ever end up making a PR for this? Even a work in progress one? I'm trying to solve the same issue (I'm making a horizontal menu too)

**Comment by jamsea** [comment]
@diegohaz and @davidtheclark got it working 👍  PR is here: https://github.com/davidtheclark/react-aria-menubutton/pull/66

**Comment by davidtheclark** [comment]
Closed by #66.
