### ISSUE TITLE
Focus on First Menu Item when Menu is opened

### ISSUE THREAD

**Issue by LeopoldoFu** [davidtheclark/react-aria-menubutton#51]
According to [wai-aria practices](https://www.w3.org/TR/wai-aria-practices/#menu), the first menu-item should be focused whenever the menu is opened:

> When a menu opens and its items are arranged vertically:
> 
> Keyboard focus is placed on the first item. All items in a menu are focusable as described in 4.1.3 > Keyboard Navigation within Widgets.

Should this functionality be baked into this library or handled by the consumer of this component?

If consumers should handle it, then I have a [fork of this library](https://github.com/ebsco/react-aria-menubutton/pull/1) that exposes `focusItem` through `externalStateControl.focusItem`.

**Comment by davidtheclark** [comment]
Huh, looks like the document has received an update. The functionality should be updated in the library to match.

**Comment by LeopoldoFu** [comment]
Working on it.

**Comment by vnglst** [comment]
Hi @davidtheclark. Currently the openMenu function let's you focus the menu manually (using the openOptions' focusMenu boolean). In the previous PR this functionality was removed, probably because the menu always gets the focus automatically.

Do you think this is a good idea? It's a breaking change for one, and NOT setting the focus might be an option you'd actually want. What do you think?

**Comment by vnglst** [comment]
Implemented in PR #61 (and available in version 5)
